from pathlib import Path
import json

items = [
    {"id": 1, "hanzi": "行政", "pinyin": "xíngzhèng", "indonesian": "Administrasi", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 2, "hanzi": "文件", "pinyin": "wénjiàn", "indonesian": "Dokumen", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 3, "hanzi": "系统", "pinyin": "xìtǒng", "indonesian": "Sistem", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 4, "hanzi": "数据库", "pinyin": "shùjùkù", "indonesian": "Database", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 5, "hanzi": "数据", "pinyin": "shùjù", "indonesian": "Data", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 6, "hanzi": "归档", "pinyin": "guīdàng", "indonesian": "Pengarsipan", "category": "Administration", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 7, "hanzi": "协调", "pinyin": "xiétiáo", "indonesian": "Koordinasi", "category": "Administration", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 8, "hanzi": "统计", "pinyin": "tǒngjì", "indonesian": "Pendataan", "category": "Administration", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 9, "hanzi": "合同", "pinyin": "hétóng", "indonesian": "Kontrak", "category": "Contract", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 10, "hanzi": "销售合同", "pinyin": "xiāoshòu hétóng", "indonesian": "Kontrak Penjualan", "category": "Contract", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 11, "hanzi": "订单合同", "pinyin": "dìngdān hétóng", "indonesian": "Kontrak Pesanan", "category": "Contract", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 12, "hanzi": "结算合同", "pinyin": "jiésuàn hétóng", "indonesian": "Kontrak Penyelesaian", "category": "Contract", "level": "Advanced", "favorite": False, "mastered": False},
    {"id": 13, "hanzi": "起草", "pinyin": "qǐcǎo", "indonesian": "Menyusun draft", "category": "Contract", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 14, "hanzi": "提交系统", "pinyin": "tíjiāo xìtǒng", "indonesian": "Mengajukan ke sistem", "category": "Contract", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 15, "hanzi": "供应商", "pinyin": "gōngyìngshāng", "indonesian": "Supplier", "category": "Supplier", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 16, "hanzi": "供应商注册", "pinyin": "gōngyìngshāng zhùcè", "indonesian": "Registrasi supplier", "category": "Supplier", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 17, "hanzi": "供应商准入", "pinyin": "gōngyìngshāng zhǔnrù", "indonesian": "Akses supplier", "category": "Supplier", "level": "Advanced", "favorite": False, "mastered": False},
    {"id": 18, "hanzi": "供应商维护", "pinyin": "gōngyìngshāng wéihù", "indonesian": "Pemeliharaan supplier", "category": "Supplier", "level": "Advanced", "favorite": False, "mastered": False},
    {"id": 19, "hanzi": "供应商评估", "pinyin": "gōngyìngshāng pínggū", "indonesian": "Evaluasi supplier", "category": "Supplier", "level": "Advanced", "favorite": False, "mastered": False},
    {"id": 20, "hanzi": "文件更新", "pinyin": "wénjiàn gēngxīn", "indonesian": "Pembaruan dokumen", "category": "Supplier", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 21, "hanzi": "考察报告", "pinyin": "kǎochá bàogào", "indonesian": "Laporan survei", "category": "Supplier", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 22, "hanzi": "人力资源", "pinyin": "rénlì zīyuán", "indonesian": "Sumber Daya Manusia", "category": "HR", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 23, "hanzi": "招聘", "pinyin": "zhāopìn", "indonesian": "Rekrutmen", "category": "HR", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 24, "hanzi": "候选人", "pinyin": "hòuxuǎnrén", "indonesian": "Kandidat", "category": "HR", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 25, "hanzi": "简历", "pinyin": "jiǎnlì", "indonesian": "Resume", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 26, "hanzi": "初步筛选", "pinyin": "chūbù shāixuǎn", "indonesian": "Pre-screening", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 27, "hanzi": "面试", "pinyin": "miànshì", "indonesian": "Wawancara", "category": "HR", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 28, "hanzi": "新员工", "pinyin": "xīn yuángōng", "indonesian": "Karyawan Baru", "category": "HR", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 29, "hanzi": "入职培训", "pinyin": "rùzhí péixùn", "indonesian": "Pelatihan Onboarding", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 30, "hanzi": "试用期", "pinyin": "shìyòngqī", "indonesian": "Masa Probation", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 31, "hanzi": "绩效考核", "pinyin": "jìxiào kǎohé", "indonesian": "Penilaian Kinerja", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 32, "hanzi": "廉洁", "pinyin": "liánjié", "indonesian": "Integritas", "category": "HR", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 33, "hanzi": "考勤", "pinyin": "kǎoqín", "indonesian": "Kehadiran", "category": "Attendance", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 34, "hanzi": "考勤汇总", "pinyin": "kǎoqín huìzǒng", "indonesian": "Rekap Kehadiran", "category": "Attendance", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 35, "hanzi": "加班", "pinyin": "jiābān", "indonesian": "Lembur", "category": "Attendance", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 36, "hanzi": "工资", "pinyin": "gōngzī", "indonesian": "Gaji", "category": "Attendance", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 37, "hanzi": "资产", "pinyin": "zīchǎn", "indonesian": "Aset", "category": "Asset", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 38, "hanzi": "资产盘点", "pinyin": "zīchǎn pándiǎn", "indonesian": "Inventarisasi Aset", "category": "Asset", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 39, "hanzi": "文件柜", "pinyin": "wénjiànguì", "indonesian": "Lemari Arsip", "category": "Asset", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 40, "hanzi": "电脑", "pinyin": "diànnǎo", "indonesian": "Komputer", "category": "Asset", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 41, "hanzi": "笔记本电脑", "pinyin": "bǐjìběn diànnǎo", "indonesian": "Laptop", "category": "Asset", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 42, "hanzi": "打印机", "pinyin": "dǎyìnjī", "indonesian": "Printer", "category": "Asset", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 43, "hanzi": "碎纸机", "pinyin": "suìzhǐjī", "indonesian": "Mesin Penghancur Kertas", "category": "Asset", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 44, "hanzi": "硬盘", "pinyin": "yìngpán", "indonesian": "Hard Disk", "category": "Asset", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 45, "hanzi": "资产数据库", "pinyin": "zīchǎn shùjùkù", "indonesian": "Database Aset", "category": "Asset", "level": "Advanced", "favorite": False, "mastered": False},
    {"id": 46, "hanzi": "责任人", "pinyin": "zérènrén", "indonesian": "Penanggung Jawab", "category": "Asset", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 47, "hanzi": "会议室", "pinyin": "huìyìshì", "indonesian": "Ruang Rapat", "category": "Office", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 48, "hanzi": "会议室预订", "pinyin": "huìyìshì yùdìng", "indonesian": "Reservasi Ruang Rapat", "category": "Office", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 49, "hanzi": "住宿安排", "pinyin": "zhùsù ānpái", "indonesian": "Pengaturan Akomodasi", "category": "Office", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 50, "hanzi": "餐饮安排", "pinyin": "cānyǐn ānpái", "indonesian": "Pengaturan Konsumsi", "category": "Office", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 51, "hanzi": "工作计划", "pinyin": "gōngzuò jìhuà", "indonesian": "Rencana Kerja", "category": "Planning", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 52, "hanzi": "目标", "pinyin": "mùbiāo", "indonesian": "Target", "category": "Planning", "level": "Beginner", "favorite": False, "mastered": False},
    {"id": 53, "hanzi": "标准作业程序", "pinyin": "biāozhǔn zuòyè chéngxù", "indonesian": "SOP", "category": "Planning", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 54, "hanzi": "进度跟踪", "pinyin": "jìndù gēnzōng", "indonesian": "Tracking Progress", "category": "Planning", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 55, "hanzi": "时间管理", "pinyin": "shíjiān guǎnlǐ", "indonesian": "Manajemen Waktu", "category": "Planning", "level": "Intermediate", "favorite": False, "mastered": False},
    {"id": 56, "hanzi": "中文能力", "pinyin": "zhōngwén nénglì", "indonesian": "Kemampuan Bahasa Mandarin", "category": "Planning", "level": "Intermediate", "favorite": False, "mastered": False},
]

out = Path('src/data/users/feiza.json')
out.write_text(json.dumps(items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Wrote {len(items)} items to {out}')
